logging:
  level:
    root: info
    web: error
debug: false
spring:
  application:
    name: demo
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: test
      username: test
      password: test
  devtools:
    livereload:
      enabled: true
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
server:
  port: 8085
  ssl:
    enabled: false

